/**
 * Generate Tool Type Union from Implementations
 *
 * This script automatically generates the Tool type union by scanning
 * tool implementations in src/lib/tools/implementations/
 *
 * Run: npm run generate:types
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toolsDir = path.join(__dirname, '../src/lib/tools/implementations');
const outputFile = path.join(__dirname, '../src/lib/types/generated-tool-types.ts');

interface ToolInfo {
	id: string;
	fileName: string;
}

async function generateToolTypes() {
	console.log('🔧 Generating tool types...\n');

	// Read all tool implementation files
	const files = fs.readdirSync(toolsDir).filter((f) => f.endsWith('.ts'));

	console.log(`📁 Found ${files.length} tool files in ${toolsDir}\n`);

	const tools: ToolInfo[] = [];

	// Extract tool IDs from each file
	for (const file of files) {
		const filePath = path.join(toolsDir, file);
		const content = fs.readFileSync(filePath, 'utf-8');

		// Match: id: 'toolname'
		const idMatch = content.match(/id:\s*['"]([^'"]+)['"]/);

		if (idMatch) {
			const toolId = idMatch[1];
			tools.push({ id: toolId, fileName: file });
			console.log(`  ✓ ${file.padEnd(25)} → id: '${toolId}'`);
		} else {
			console.warn(`  ⚠ ${file.padEnd(25)} → No id found!`);
		}
	}

	console.log(`\n✅ Extracted ${tools.length} tool IDs\n`);

	// Sort tools alphabetically by ID
	tools.sort((a, b) => a.id.localeCompare(b.id));

	// Generate TypeScript output
	const toolIds = tools.map((t) => t.id);
	const timestamp = new Date().toISOString();

	const output = `/**
 * Auto-generated Tool Types
 *
 * ⚠️ DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-tool-types.ts
 * Generated at: ${timestamp}
 * Run: npm run generate:types
 *
 * This file is automatically generated from tool implementations.
 * Any manual changes will be overwritten on next generation.
 */

/**
 * Union type of all registered tool IDs
 */
export type Tool = ${toolIds.map((id) => `'${id}'`).join(' | ')};

/**
 * Array of all registered tool IDs (const assertion for literal types)
 */
export const REGISTERED_TOOLS = [${toolIds.map((id) => `'${id}'`).join(', ')}] as const;

/**
 * Type derived from REGISTERED_TOOLS array
 */
export type RegisteredTool = (typeof REGISTERED_TOOLS)[number];

/**
 * Tool metadata for reference
 */
export const TOOL_METADATA = {
${tools
	.map(
		(tool) => `\t'${tool.id}': {
\t\tid: '${tool.id}',
\t\tfile: '${tool.fileName}'
\t}`
	)
	.join(',\n')}
} as const;
`;

	// Write output file
	fs.writeFileSync(outputFile, output, 'utf-8');

	console.log(`📝 Generated type file:`);
	console.log(`   ${outputFile}\n`);

	console.log(`📊 Summary:`);
	console.log(`   Total tools: ${tools.length}`);
	console.log(`   Tool IDs: ${toolIds.join(', ')}\n`);

	console.log('✨ Type generation complete!\n');
}

// Run the generator
generateToolTypes().catch((error) => {
	console.error('❌ Error generating tool types:', error);
	process.exit(1);
});
