/**
 * Auto-generated Tool Types
 *
 * ⚠️ DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-tool-types.ts
 * Generated at: 2025-12-05T14:59:45.743Z
 * Run: npm run generate:types
 *
 * This file is automatically generated from tool implementations.
 * Any manual changes will be overwritten on next generation.
 */

/**
 * Union type of all registered tool IDs
 */
export type Tool = 'bucket' | 'eraser' | 'eyedropper' | 'hand' | 'move' | 'pencil';

/**
 * Array of all registered tool IDs (const assertion for literal types)
 */
export const REGISTERED_TOOLS = ['bucket', 'eraser', 'eyedropper', 'hand', 'move', 'pencil'] as const;

/**
 * Type derived from REGISTERED_TOOLS array
 */
export type RegisteredTool = (typeof REGISTERED_TOOLS)[number];

/**
 * Tool metadata for reference
 */
export const TOOL_METADATA = {
	'bucket': {
		id: 'bucket',
		file: 'BucketTool.ts'
	},
	'eraser': {
		id: 'eraser',
		file: 'EraserTool.ts'
	},
	'eyedropper': {
		id: 'eyedropper',
		file: 'EyedropperTool.ts'
	},
	'hand': {
		id: 'hand',
		file: 'HandTool.ts'
	},
	'move': {
		id: 'move',
		file: 'MoveTool.ts'
	},
	'pencil': {
		id: 'pencil',
		file: 'PencilTool.ts'
	}
} as const;
